
<style>
	
	body{
		padding:0px;
		margin:0px;
		background-color: #F8F8F8;
		
	}
   #home
    {
			z-index: 4;
			margin-left: auto;
			margin-right: auto;
			width:350px;
			font-family: Arial ;
			position: relative;		
    }
	
	#back
    {
		z-index: 2;
		position: absolute;
		height:100%;
		width:100%;
		margin-left: auto;
		margin-right: auto;
		
    }
	#logo
    {
		margin-left: auto;
		margin-right: auto;
		width: 300px;
		height: 300px;	
    }
	
	.vertical-menu {
		margin-left: auto;
		margin-right: auto;
		width: 100%; /* Set a width if you like */
	}

	.vertical-menu a {
		background-color: black; /* Grey background color */
		color: white; /* Black text color */
		display: block; /* Make the links appear below each other */
		padding: 12px; /* Add some padding */
		text-decoration: none; /* Remove underline from links */
		margin-bottom:5px;
		border-radius:20px;
	}

	.vertical-menu a:hover {
		background-color: #ccc; /* Dark grey background on mouse-over */
	}

	.vertical-menu a.active {
		background-color: #4CAF50; /* Add a green color to the "active/current" link */
		color: white;
	}
	p
	{
		font-size: 14px;
		margin-top:10%;;
	}
	
	.inscription{
		margin-top:10px;
		padding: 8px;
		width:100px;
		border: 1px solid #666;
		background: #ffffff;
		font-size: 12px;
		border-radius:5px;
		
	}
	a:link {
    text-decoration: none;
	}
}
  
</style>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <title>Geo-Quizz</title>

</head>
<body>



		<div id="home">
			<img src="../../../image/logo.png" id="logo" alt="Mountain View">	
			<form class="w3-container">	
				<div id="menu">
				
					<div class="vertical-menu">
						<p>E-mail</p>
						<input class="w3-input w3-animate-input  w3-light-grey" type="text" style="width:100%">
						<p>Mot de passe</p>
						<input class="w3-input w3-animate-input  w3-light-grey" type="password" style="width:100%">
					</div>		
					
					<div class="inscription"><a href="#">Se connecter</a><div>
					
				</div>
				
			</form>
		</div>
		<p>Pas encore de compte chez nous ?<a href="#"> Inscrivez-vous.</a> </p>

</body>

	
</html>
