<style>
	
	body{
		padding:0px;
		margin:0px;
		
	}
   #home
    {
			z-index: 4;
			margin-left: auto;
			margin-right: auto;
			width:300px;
			font-family: Arial ;
			position: relative;		
    }
	
	#back
    {
		z-index: 2;
		position: absolute;
		height:100%;
		width:100%;
		margin-left: auto;
		margin-right: auto;
		
    }
	#logo
    {
		margin-left: auto;
		margin-right: auto;
		width: 300px;
		height: 300px;	
    }
	
	.vertical-menu {
		margin-left: auto;
		margin-right: auto;
		width: 200px; /* Set a width if you like */
	}

	.vertical-menu a {
		background-color: black; /* Grey background color */
		color: white; /* Black text color */
		display: block; /* Make the links appear below each other */
		padding: 12px; /* Add some padding */
		text-decoration: none; /* Remove underline from links */
		margin-bottom:5px;
		border-radius:20px;
	}

	.vertical-menu a:hover {
		background-color: #ccc; /* Dark grey background on mouse-over */
	}

	.vertical-menu a.active {
		background-color: #4CAF50; /* Add a green color to the "active/current" link */
		color: white;
	}
	
  
</style>

<?php echo $this->doctype(); $bdd = new Zend_Db_Adapter_Pdo_Mysql(array(
    'host'     => 'localhost',
    'username' => 'root',
    'password' => 'root',
    'dbname'   => 'geo_quizz_bd'
));?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Geo-Quizz</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>


<?php /*echo $this->layout()->content */?>
		<img src="../application/image/back_ground.jpg" id="back" alt="Mountain View">

		<div id="home">
			
					<img src="../application/image/logo.png" id="logo" alt="Mountain View">
				<div id="menu">
					<div class="vertical-menu">

						  
				<a href="<?php echo $this->url(
            array('controller'=>'solo'),
            'default',
            true) ?>">Solo</a>
						  <a href="geo_quizz/application/views/scripts/index/solo.phtml">Multijoueur</a>
						  <a href="#">Parametre</a>
						  <a href="#">Inviter</a>
					</div>			
				</div>
				
		</div>
	



</body>

</html>


